name: SocialButterly
favicon: null
layout_spectrum: 0.5148346000351012
typography_spectrum: 0.00505672232247889
title: Social Butterfly
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9462939570657909
  lightness: 0.7217509620822966
  saturation: 0.7835984395351261
  rhythmicContrast: 0.9167030942626297
purpose: []
